version: "3.9"

services:
  localstack:
    image: localstack/localstack:1.2.0
    ports:
      - 4566:4566
    environment:
      - EAGER_SERVICE_LOADING=1
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
